######################################

# This script defines the project pipeline - it specifies the execution orders for all the code in this
# repo using a series of actions.

######################################


version: '3.0'

expectations:
  population_size: 100000

actions:

# Generate study population and extract baseline characteristics 
  generate_study_pop_baseline:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_baseline
      --index-date-range "2022-09-03" 
      --output-dir=feather 
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_baseline_*.feather
        
# Generating study population at different index dates 
  generate_study_pop_index_1:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_index
      --index-date-range "2022-09-03" 
      --output-dir=feather 
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_index_*.feather
        
# # Generating study population at different index dates 
#   generate_study_pop_index_2:
#     run: cohortextractor:latest generate_cohort
#       --study-definition study_definition_index
#       --index-date-range "2022-10-15" 
#       --output-dir=feather 
#       --output-format=feather
#     outputs:
#       highly_sensitive:
#         cohort: output/input_index*.feather

# # Generating study population at different index dates 
#   generate_study_pop_index_3:
#     run: cohortextractor:latest generate_cohort
#       --study-definition study_definition_index
#       --index-date-range "2022-11-26" 
#       --output-dir=feather 
#       --output-format=feather
#     outputs:
#       highly_sensitive:
#         cohort: output/input_inde*.feather

# Data processing
  data_process_baseline:
    run: r:latest analysis/processing/data_processing_baseline.R
    needs: [generate_study_pop_baseline]
    outputs:
      highly_sensitive:
        cohort: output/cohort/cohort_*.csv
      moderately_sensitive:
        descriptive: output/descriptive/total_*.csv

# Data processing
  data_process_index:
    run: r:latest analysis/processing/data_processing_index.R
    needs: [generate_study_pop_index_1]
    outputs:
      moderately_sensitive:
        descriptive: output/descriptive/num_outcomes*.csv

# Discontinuity of demographics
  demographics:
   run: r:latest analysis/descriptive/demographics_byage.R
   needs: [generate_study_pop_baseline, data_process_baseline]
   outputs:
      moderately_sensitive:
        measures_csv: output/descriptive/demographics_*.csv


# Cumulative uptake of fourth dose #
  # cumulative_fourth_dose:
  #  run: r:latest analysis/descriptive/cumulative_vax_byage.R
  #  needs: [data_process]
  #  outputs:
  #     moderately_sensitive:
  #       rates_csv: output/cumulative_rates/final_*.csv 
  #       plot: output/cumulative_rates/plot_*.png

# Flu vaccine uptake #
  # flu_vax:
  #  run: r:latest analysis/descriptive/flu_vax_byage.R
  #  needs: [generate_study_pop]
  #  outputs:
  #     moderately_sensitive:
  #       measure_csv: output/cumulative_rates/flu_*.csv
  #       plot: output/cumulative_rates/plot_flu_vax_byage.png


# Outcome plots #
  # covid_outcomes:
  #  run: r:latest analysis/descriptive/covid_outcomes_byage.R
  #  needs: [generate_study_pop]
  #  outputs:
  #     moderately_sensitive:
  #       measure_csv: output/covid_outcomes/covid_*.csv
  #       plot: output/covid_outcomes/plot_outcomes_*.png
  

# ITT analysis #


# IV analysis #



  
